var res = {
    BackGround_png: "res/start/background.png",
    Start_N_png: "res/start/start_N.png",
    Start_S_png: "res/start/start_S.png",
    Setting_N_png: "res/start/setting_N.png",
    Setting_S_png: "res/start/setting_S.png",
    Rank_N_png: "res/start/rank_N.png",
    Rank_S_png: "res/start/rank_S.png",

    MainBackground_png: "res/main/background.png",
    PlayerBg_png: "res/main/player_bg.png",
    Player1_N_png: "res/main/player1_N.png",
    Player1_D_png: "res/main/player1_D.png",
    Player1_title_png: "res/main/player1_title.png",
    Player2_N_png: "res/main/player2_N.png",
    Player2_D_png: "res/main/player2_D.png",
    Player2_title_png: "res/main/player2_title.png",
    CardNum_png: "res/main/card_num.png",
    CardBtn_N_png: "res/main/card_btn_N.png",
    CardBtn_S_png: "res/main/card_btn_S.png",
    RandomBtn_N_png: "res/main/random_btn_N.png",
    RandomBtn_S_png: "res/main/random_btn_S.png",
    SiteDesc_png: "res/main/site_desc.png",
    RuleDesc_png: "res/main/rule_desc.png",
    SiteNo_png: "res/main/site_no.png",
    SitePass_png: "res/main/site_pass.png",
    SiteStop_png: "res/main/site_stop.png",
    SiteMove_png: "res/main/site_move.png",
    Shadow_png: "res/shadow.png",

    RandomBox1_png: "res/random/1.png",
    RandomBox2_png: "res/random/2.png",
    RandomBox3_png: "res/random/3.png",
    RandomBox4_png: "res/random/4.png",
    RandomBox5_png: "res/random/5.png",
    RandomBox6_png: "res/random/6.png",
    RandomYes_N_png: "res/random/yes_N.png",
    RandomYes_S_png: "res/random/yes_S.png",

    CardGet_png: "res/card/card_get.png",
    CardBg_png: "res/card/card_bg.png",
    CardToSelf_N_png: "res/card/card_to_self_N.png",
    CardToSelf_S_png: "res/card/card_to_self_S.png",
    CardToOther_N_png: "res/card/card_to_other_N.png",
    CardToOther_S_png: "res/card/card_to_other_S.png",
    CardClose_N_png: "res/card/close_N.png",
    CardClose_S_png: "res/card/close_S.png",
    CardRule_1_png: "res/card/card_rule_1.png"
};
